### ISSUE TITLE
4D light-field material dataset

### ISSUE THREAD

**Issue by DongHappyyy** [maoshangbo/DRP-Texture-Recognition#3]
Hello, I'm very sorry to disturb you. I've been reading your paper recently, and I've gained a lot. I take the liberty to ask if you can share the download link of 4D light dataset. I searched the Internet for a long time and couldn't find the 4dlight dataset. Thank you again

**Comment by maoshangbo** [comment]
Please check http://cseweb.ucsd.edu/~viscomp/projects/LF/papers/ECCV16/LF_dataset.zip.

**Comment by DongHappyyy** [comment]
Thank you very much！It helped me a lot,.  Have a good time！
