### ISSUE TITLE
The precision in the paper cannot be reached on the DTD dataset

### ISSUE THREAD

**Issue by DongHappyyy** [maoshangbo/DRP-Texture-Recognition#4]
Hello, excuse me again. I used the code you provided to train on the DTD dataset, but the training accuracy was still less than 73.44% (resnet50) in the paper. I used the 10 train-test splits officially provided. I would like to ask what is the reason for the poor accuracy. My training results are only about 68%. Do you train on the officially provided train-test or train-val? Does the data need other preprocessing？

**Comment by maoshangbo** [comment]
Yes, I trained on the officially provided train+val set and tested on test set, according to the setting in https://www.robots.ox.ac.uk/~vgg/data/dtd/download/desctex.tar.gz. 

No pre-processing needed.

**Comment by DongHappyyy** [comment]
Thank you very much for your reply! I only used train set for training, test set for testing, and did not use val set, which may be the reason why my training effect is not good. Thanks a lot for your guidance.
